OVS_Packager_Batch_Import/CSVImport/CSVImport/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
# Examples:
    # url(r'^$', 'CSVImport.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^main/', include('main.urls', namespace="main", app_name="main")),
    url(r'^$', include('main.urls', namespace="main", app_name="main")),                       
    # attempt to add views
    #  url(r'^BatchJob/', include('CSVImport'))
)

OVS_Packager_Batch_Import/CSVImport/main/urls.py
from django.conf.urls import patterns, include, url
# from main import views

urlpatterns = patterns('', 
	url(r'^$', 'main.views.home', name='home'),
	url(r'^latestbatchview/$', 'main.views.latestbatchview', name='latestbatchview'),
    url(r'^(?P<batch_id>\d+)/$', 'main.views.batchview', name='batchview'),                       
    url(r'^(?P<batch_id>\d+)/batchview/$', 'main.views.batchview', name='batchview'),
)

OVS_Packager_Batch_Import/CSVImport/CSVImporter/models.py
from django.db import models

# Create your models here.

OVS_Packager_Batch_Import/CSVImport/main/models.py
from django.db import models
import OVSPackager_CLItools as CLI
#from csvimport.models import CSVimport
# Create your models here.
 
 
class UploadFile(models.Model):
    file = models.FileField(upload_to='files/%Y/%m/%d')

class PackJob(models.Model):
    prodid = models.CharField(max_length=12)
    title = models.CharField(max_length=300)
    name = models.CharField(max_length=300)
    asset_type = models.CharField(max_length=10) #consider making this a choice field
    priority = models.IntegerField(unique=False) 
    response = models.CharField(max_length=300, default="none - not yet submitted")
    # def __init__(self):
    #     self.response = "not submitted"
    def __unicode__(self):
        return self.name
    def is_packaged(self):
        return CLI.is_packaged(self.prodid)
    def is_in_queue(self):
        return CLI.is_in_queue(self.prodid)    
    def package(self):
        if self.is_in_queue():
            self.response = "already in packager queue"
        elif self.is_packaged():
            self.response = "already packaged"
        else:
            job_dict = {}
            job_dict['prod_id'] = self.prod_id
            job_dict['title'] = self.title
            job_dict['asset_type'] = self.asset_type
            job_dict['priority'] = self.priority
            submitter = CLI.submit_job(job_dict)

            self.response = submitter['response']
                # print self.response   
            # return self   
    ##column1=prodid, column2=title, column3=asset_type, column4=priority

class BatchJob(models.Model):
    name = models.CharField(max_length=400)
    job_list = models.ManyToManyField(PackJob) #should hold packjob objects
    def __unicode__(self):
        return self.name
    def package(self):
        for job in self.job_list.all():
            job.package()

OVS_Packager_Batch_Import/CSVImport/CSVImport/forms.py
from django import forms

class UploadFileForm(forms.Form):
    title = forms.CharField(max_length=50)
    file = forms.FileField()

class CSVImportForm(forms.Form):
    # File size limited to 2MB
    file = RestrictedFileField(
    #from .fields
        label='CSV File (Max Size 2MB)',
        content_types=['text/csv', 'application/csv'],
        max_upload_size=2097152,
    )

    def __init__(self, *args, **kwargs):
        super(CSVImportForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_method = 'post'

        self. helper.layout = Layout(
            MultiField(
                None,
                Fieldset(
                    'Instructions',
                    HTML(
                        '''
                        To properly import your data, the CSV file must follow
                        this order and format: <br><br>
                        <ol>
                        <li>Value</li>
                        <li>Category (if no matching category in our system,
                        'No Category' will be assigned)</li>
                        <li>Date (in m/d/yyyy format, e.g. 5/6/2014 or
                        05/06/2014)</li>
                        <li> Time (in h:m am/pm format, e.g. 8:01 AM or
                        08:01 PM)</li>
                        <li>Notes</li>
                        </ol>
                        <p>You can also download this template as a guide:
                        <a href="{{ STATIC_URL }}samples/csv_import_template.csv">
                        csv_import_template.csv</a></p>
                        <br>
                        '''
                    ),
                ),
                HTML(
                    '''
                    {% if messages %}
                    {% for message in messages %}
                    <p {% if message.tags %}
                    class="alert alert-{{ message.tags }}"
                    {% endif %}>{{ message }}</p>{% endfor %}{% endif %}
                    '''
                ),
                Div(
                    'file',
                    FormActions(
                        Submit('submit', 'Import'),
                        css_class='pull-right',
                    ),
                    css_class='well col-xs-10 col-sm-8 col-md-8',
                ),
            ),
        )

class BatchJobForm(forms.Form):
    pass

OVS_Packager_Batch_Import/CSVImport/main/forms.py
from django import forms
from models import UploadFile, BatchJob

#for dropzone:   
class UploadFileForm(forms.ModelForm):   
    class Meta:
        model = UploadFile

#     file = forms.FileField()

# class UploadFileForm(forms.Form):
# #     title = forms.CharField(max_length=50)
#     file = forms.FileField()

class BatchForm(forms.ModelForm):
    class Meta:
        model = BatchJob

OVS_Packager_Batch_Import/CSVImport/CSVImporter/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View 

# class BatchJobView(View):
# 	def get(self, request):
# 	# view logic
# 		return HttpResponse('result')

OVS_Packager_Batch_Import/CSVImport/main/views.py
from django.shortcuts import render, redirect, render_to_response, get_object_or_404

from django.http import HttpResponseRedirect, HttpResponse
from django.template import RequestContext
from django.core.urlresolvers import reverse

from .utils import csv_to_job_list, batch_maker
from main.models import PackJob, BatchJob

from django.forms import ModelForm


from forms import UploadFileForm
from models import UploadFile

# Create your views here.

 
def home(request):
    if request.method == 'POST':
        form = UploadFileForm(request.POST, request.FILES) # form bound to post data
        if form.is_valid():
            new_file = UploadFile(file = request.FILES['file'])
            new_file.save()
            batch_job = batch_maker(request.FILES['file']) #builds packjob and jobs, returns BatchJob object
            return HttpResponseRedirect(reverse('main:batchview', args=(batch_job.id,)))
    else:
        form = UploadFileForm()
        data = {'form': form}
    
    return render_to_response('main/index.html', data, context_instance=RequestContext(request))
    #return HttpResponse("test")

def latestbatchview(request):
    if request.method == 'GET':
        batch_job = get_object_or_404(BatchJob, pk=BatchJob.objects.last().id)
        return render_to_response('main/batchview.html', {'batch_job' : batch_job})     

def batchview(request, batch_id):
#     return HttpResponse('test')
#     if request.method =='POST':
    batch_job = get_object_or_404(BatchJob, pk=batch_id)
    return render_to_response('main/batchview.html', {'batch_job' : batch_job})
#     return HttpResponse("Your're looking at the contents of batch %s." % batch_id)
#     job_list = request.body
#     context = {'batch_id' : batch_id}
#     return render_to_response('main/batchview.html')
    
    

OVS_Packager_Batch_Import/CSVImport/main/templates/main/batchview.html
<!DOCTYPE html>
<html>
    <head>
        
    </head>
    <body>
        Here is the batch:
        </br>
        <ul><li>{{ batch_job }}</li></ul>
        </br>
    <br>
    <div id="package all">Package All</div>
    <div id="main"><a href="/main">Main</a></div>
    <br>
        Here are the jobs:
        <table>
            <tr>
                <th>Job Name</th>
                <th>Priority</th>
                <th>Is In Queue?</th>
                <th>Is Packaged?</th>
                <th>Response</th>
            </tr>
            {% for job in batch_job.job_list.all %}
            <tr>
                <td>{{ job.title }}</td>
                <td>{{ job.priority }}</td>
                <td>{{ job.is_in_queue }}</td>
                <td>{{ job.is_packaged }}</td>
                <td>{{ job.response }}</td>
            </tr>
        {% endfor %}
        </table></ul>
    </body>
</html>

OVS_Packager_Batch_Import/CSVImport/main/templates/main/index.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Upload a file in Django 1.5 using Dropzone.js</title>
        {% load staticfiles %}
        <link href="{% static 'main/css/dropzone.css' %}" type="text/css" rel="stylesheet"/>
    </head>
    <body>
        <h1>Drop Formatted CSV batch files here</h1>
        <p>Some text describing formatting</p>
        <p>maybe a screenshot</p>
        <!-- IMPORTANT enctype attribute! -->
        <form id="my-awesome-dropzone" class="dropzone" action="{% url "main:home" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
<!--             {{ form }} -->
        </form>
        <p>Click Submit to generate a table view showing the batch</p>
        <button id="submit-all">
            Submit all files
        </button>
        <script src="{% static 'main/js/dropzone.js' %}"></script>
        <script type="text/javascript">
            Dropzone.options.myAwesomeDropzone = {
                paramName: "file",
                // Prevents Dropzone from uploading dropped files immediately
                autoProcessQueue : true,
                maxFiles : 1,                                 
                acceptedFiles : ".csv",
                
                init : function() {
                    // this.on("success", function(responseText) {
                    //     window.alert(responseText)

//                     this.on('complete', function () {
//                         location.reload();
//                     });
                
                    this.on("success", function() {
                        window.location.href = "/main/latestbatchview";
                    }
                           )
                
                    myAwesomeDropzone = this;
                    var submitButton = document.querySelector("#submit-all");
                    submitButton.addEventListener("click", function() {
                        myAwesomeDropzone.processQueue();
                      //  Tell Dropzone to process all queued files.
                    });
                    
                    this.on("maxfilesexceeded", function(file){
                    alert("No more files please!");
                    })
                    // You might want to show the submit button only when
                    // files are dropped here:
                    
//                     this.on("addedfile", function() {
//                         // Show submit button here and/or inform user to click it.
                        
            }}
                            
                
            
//             uncomment below to turn DZ off
//             Dropzone.options.myAwesomeDropzone = false
        </script>
        
 
    </body>
</html>

OVS_Packager_Batch_Import/CSVImport/main/templates/main/index_dropzone.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Upload a file in Django 1.5 using Dropzone.js</title>
        {% load staticfiles %}
        <!-- <link href="{% static 'main/css/dropzone.css' %}" type="text/css" rel="stylesheet"/> -->
    </head>
    <body>
        <h1>Drop Formatted CSV batch files here</h1>
        <p>Some text describing formatting</p>
        <p>maybe a screenshot</p>
        <!-- IMPORTANT enctype attribute! -->
        <form class="dropzone" action="{% url "main:home" %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        </form>
        <p>Click Submit to generate a table view showing the batch</p>
        <button id="submit-all">
            Submit all files
        </button>
 
        <script src="{% static 'main/js/dropzone.js' %}"></script>
        <script type="text/javascript">
            Dropzone.options.myDropzone = {
 
                // Prevents Dropzone from uploading dropped files immediately
                autoProcessQueue : true,
 
                init : function() {
                    var submitButton = document.querySelector("#submit-all")
                    myDropzone = this;
 
                    submitButton.addEventListener("click", function() {
                        myDropzone.processQueue();
                        // Tell Dropzone to process all queued files.
                    });
 
                    // You might want to show the submit button only when
                    // files are dropped here:
                    this.on("dz-success", function() {
                        window.location.href = "/main/latestbatchview";
                        // Show submit button here and/or inform user to click it.
                    });
 
                }
            };
        </script>
    </body>
</html>

OVS_Packager_Batch_Import/CSVImport/main/templates/main/index_plain.html
<!DOCTYPE html>
<html>
    <head>
    </head>
    
    <body>
        <form>
            <form action="{% url "main:home" %}" method="post" enctype="multipart/form-data">
            {{ form }}
<!--                 {% csrf_token %} -->
            <input type="submit" value="OK">
        </form>
    </body>

OVS_Packager_Batch_Import/CSVImport/main/templates/main/response.html
<!DOCTYPE html>
<html>
	{% response_table %}
	<a href="ovspackager.indemand.com">Packager Job Queue</a>
</html>